### ISSUE TITLE
Order request returning Invalid Body

### ISSUE THREAD

**Issue by ashtonaureleo123** [IIFLSecurities/TradingAPIs#23]
test_order = Order(order_type="BUY", scrip_code=2885, quantity=100, exchange="N",
                           exchange_segment="C", price=64, is_intraday=False, atmarket=False,
                           exch_order_id="0", DisQty=0, stoploss_price=0,
                           is_stoploss_order=False, ioc_order=False, is_vtd=False, ahplaced=AHPlaced.NORMAL_ORDER,
                           public_ip='192.168.1.1', order_validity=OrderValidity.DAY, traded_qty=0)
        x=self.client.place_order(order=test_order, client_id=CLIENT_ID, order_requester_code='order_requester_code')

I receive message as Invalid body.
 12:43:48 | {'BrokerOrderID': 0, 'ClientCode': '', 'Exch': '\x00', 'ExchOrderID': '', 'ExchType': '\x00', 'LocalOrderID': 0, 'Message': 'Invalid body parameters.', 'RMSResponseCode': 0, 'ScripCode': 0, 'Status': 2, 'Time': '/Date(1640691828333+0530)/'}

Note: Order was placed when market was closed.

**Comment by divjainbt** [comment]
> x=self.client.place_order(order=test_order, client_id=CLIENT_ID, order_requester_code='order_requester_code')

What value are you using for 'order_requester_code' ??
I use my client code for order requester code as well, works just fine!

**Comment by ashtonaureleo123** [comment]
> > x=self.client.place_order(order=test_order, client_id=CLIENT_ID, order_requester_code='order_requester_code')
> 
> What value are you using for 'order_requester_code' ?? I use my client code for order requester code as well, works just fine!

Yes works fine when I assigned order_requestor_code as clientID.
